name: demo
on:
  push:
    tags:
      - '*'
jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Demo
        run: echo "Successfully published the artifact."
