name: Build and Deploy Web App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build the project
        run: ./gradlew wasmJsBrowserDistribution

      - name: Check out the gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages

      - name: Remove old app directory
        run: |
          rm -rf app/*

      - name: Move build artifacts to app directory
        run: |
          mv composeApp/build/dist/wasmJs/productionExecutable/* app/

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add app/
          git commit -m "Update web app"
          git push origin gh-pages