name: publish
on: workflow_dispatch
jobs:
  deploy:
    name: publish
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - name: Checkout
        id: check
        uses: actions/checkout@v4
          - name: Set up JDK
            uses: actions/setup-java@v4
            with:
              distribution: temurin
              java-version: 17
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: publishToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_IN_MEMORY_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_IN_MEMORY_KEY_PASSWORD }}
        run: ./gradlew publishToMavenCentral --no-configuration-cache
